/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// User The API Manager user is a member of organizations.
type User struct {
	// The unique identifier for the user
	Id string `json:"id,omitempty"`
	// The unique identifier for the organization to which the user belongs
	OrganizationId string `json:"organizationId,omitempty"`
	// The user's name
	Name string `json:"name,omitempty"`
	// A description of the user
	Description string `json:"description,omitempty"`
	// A unique login name for the user
	LoginName string `json:"loginName,omitempty"`
	// An email address for the user
	Email string `json:"email,omitempty"`
	// The user's phone number
	Phone string `json:"phone,omitempty"`
	// The user's mobile number
	Mobile string `json:"mobile,omitempty"`
	// The user's role, one of: user, oadmin, or admin
	Role string `json:"role,omitempty"`
	// The user's photo. To update the image, please refer to the API.
	Image string `json:"image,omitempty"`
	// Indicates whether or not the user account is enabled or not
	Enabled bool `json:"enabled,omitempty"`
	// Epoch/Unix time stamp when the organization was created
	CreatedOn int64 `json:"createdOn,omitempty"`
	// The current state of the account, one of: approved, pending
	State string `json:"state,omitempty"`
	// Indicates the type of user. Possible values: internal, external
	Type string `json:"type,omitempty"`
	AuthAttrs AuthenticatedUserAttributes `json:"authAttrs,omitempty"`
	Dn string `json:"dn,omitempty"`
}
