/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// Application API Manager application.
type Application struct {
	// The unique identifier for the application
	Id string `json:"id,omitempty"`
	// The display name for the application
	Name string `json:"name"`
	// Descriptive text for the application
	Description string `json:"description,omitempty"`
	// The organization identifier to which the application belongs
	OrganizationId string `json:"organizationId"`
	// Contact phone number of the application
	Phone string `json:"phone,omitempty"`
	// The contact email address associated with the application
	Email string `json:"email,omitempty"`
	// The unique identifier for user that created the application
	CreatedBy string `json:"createdBy,omitempty"`
	// A list of unique identifier for users that manages the application
	ManagedBy []string `json:"managedBy,omitempty"`
	// Epoch/Unix time stamp when the application was created
	CreatedOn int64 `json:"createdOn,omitempty"`
	// Flag to indicate if this application is enabled or not
	Enabled bool `json:"enabled,omitempty"`
	// URI of the image to be used for this application, this field only indicates that the application has an image assigned to it. In order to retrieve the actual image use the following URL /api/portal/applications/{id}/image/
	Image string `json:"image,omitempty"`
	// Flag to indicate if an application has been approved by the API Manager admin or if delegated then the org admin
	State string `json:"state,omitempty"`
}
