/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr

// ApplicationRequest API Manager application request.
type ApplicationRequest struct {
	// The unique identifier for the application request
	Id string `json:"id,omitempty"`
	// The display name for the application
	Name string `json:"name,omitempty"`
	// Descriptive text for the application
	Description string `json:"description,omitempty"`
	// The organization identifier to which the application request belongs
	OrganizationId string `json:"organizationId,omitempty"`
	// Contact phone number of the application
	Phone string `json:"phone,omitempty"`
	// The contact email address associated with the application
	Email string `json:"email,omitempty"`
	// URI of the image to be used for this application, this field only indicates that the application has an image assigned to it. In order to retrieve the actual image use the following URL /api/portal/organizations/{uid of org}/image/
	Image string `json:"image,omitempty"`
	// A list of unqiue API identifiers to which the application wants to use.
	Apis []string `json:"apis"`
}
