/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// BackendExport Backend API export definition.
type BackendExport struct {
	// List of backend API blobs
	ApiBlobs []BackendBlob `json:"apiBlobs,omitempty"`
}
