/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// QuotaDto The Quota is a set of restrictions that apply to applications in the Portal.
type QuotaDto struct {
	// The quota identifier
	Id string `json:"id"`
	// The quota type, either API or APPLICATION
	Type string `json:"type"`
	// The name of the quota
	Name string `json:"name"`
	// The quota for MyApplication the overrides default Application quota
	Description string `json:"description,omitempty"`
	// An array of restrictions imposed on the quota
	Restrictions []QuotaApiConstraintDto `json:"restrictions,omitempty"`
	// Indicates if the quota is system (protected)
	System bool `json:"system,omitempty"`
}
