/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// Parameter An API operation parameter for a [Method](Method.html), as part of the  [APIDefinition](APIDefinition.html).
type Parameter struct {
	// The parameter name.
	Name string `json:"name,omitempty"`
	// The parameter data type, e.g. *boolean*, *byte*, *date*, *double*, *float*, *integer*, *long*, *string*, or a type name found in [APIDefinition models](APIDefinition.html#models).
	Type string `json:"type,omitempty"`
	Format string `json:"format,omitempty"`
	Description string `json:"description,omitempty"`
	// Indicates that the parameter is required
	Required bool `json:"required,omitempty"`
	// Indicates that the parameter can be included multiple times (e.g. query or form)
	AllowMultiple bool `json:"allowMultiple,omitempty"`
	Items SchemaObject `json:"items,omitempty"`
	// Provides a default value for the parameter
	DefaultValue string `json:"defaultValue,omitempty"`
	Schema SchemaObject `json:"schema,omitempty"`
	// The parameter type, e.g. query, form, path, body, header
	ParamType string `json:"paramType,omitempty"`
}
