/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// RegistrationToken Organization Registration Token.
type RegistrationToken struct {
	// The registration code
	Token string `json:"token,omitempty"`
	// Unique identifier for the organization who the registration code applies to
	OrganizationId string `json:"organizationId,omitempty"`
	// Epoch/Unix time stamp when the registration code will expire
	Expiry int64 `json:"expiry,omitempty"`
	// Epoch/Unix time stamp when the registration code was created
	CreatedOn int64 `json:"createdOn,omitempty"`
	// The unique identifier for user that created the registration code
	CreatedBy string `json:"createdBy,omitempty"`
	// The remaining number of users that can use the registration code for self registration to an organization
	UserQuota int32 `json:"userQuota,omitempty"`
	// The total number of users that can use the registration code for self registration to an organization since the code has been created
	MaxUsers int32 `json:"maxUsers,omitempty"`
	// Flag disables registration code so that it can no longer be used for registration
	Enabled bool `json:"enabled,omitempty"`
}
