/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// QuotaApiConstraintDto The APIConstraint is restriction that applies to API(s) and API method(s).
type QuotaApiConstraintDto struct {
	// The API identifier from API discovery, or '\\*' for all API
	Api string `json:"api,omitempty"`
	// The API method identifier from API discovery, or '\\*' for all methods
	Method string `json:"method,omitempty"`
	// The restriction type, one of: throttle, throttlemb
	Type string `json:"type"`
	// The restriction configuration
	Config map[string]string `json:"config,omitempty"`
}
