/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// DiscoveryApi REST API information.
type DiscoveryApi struct {
	// The name of the API
	Name string `json:"name,omitempty"`
	// Summary of the API
	Summary string `json:"summary,omitempty"`
	// The unique identifier for the API
	Id string `json:"id,omitempty"`
	// The URL of where further information of the API is available in the portal
	Uri string `json:"uri,omitempty"`
	// The type of API, either rest or wsdl
	Type string `json:"type,omitempty"`
}
