/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// Config API Manager configuration
type Config struct {
	// The name of the API Manager.
	PortalName string `json:"portalName,omitempty"`
	// The network hostname or IP Address of the API Manager which will be used in email links.
	PortalHostname string `json:"portalHostname,omitempty"`
	// The name of the API Portal
	ApiPortalName string `json:"apiPortalName,omitempty"`
	// The network hostname or IP Address of the API Portal which will be used in email links.
	ApiPortalHostname string `json:"apiPortalHostname,omitempty"`
	// Indicates if the API Portal is configured.
	IsApiPortalConfigured bool `json:"isApiPortalConfigured,omitempty"`
	// Enables/disables user registration for the API Manager
	RegistrationEnabled bool `json:"registrationEnabled,omitempty"`
	// Enables/disables spport for resetting user passwords for the API Manager
	ResetPasswordEnabled bool `json:"resetPasswordEnabled,omitempty"`
	// The minimum password length.
	MinimumPasswordLength int32 `json:"minimumPasswordLength,omitempty"`
	// Enables/disables auto-approve for user registration whereby API Administrator or Organization Administrator approval is not required.
	AutoApproveUserRegistration bool `json:"autoApproveUserRegistration,omitempty"`
	// Enables/disables the ability to add System scopes to an Application. These scopes represent Gateway OAuth resources that are not covered by APIs.
	SystemOAuthScopesEnabled bool `json:"systemOAuthScopesEnabled,omitempty"`
	// Enables/disables auto-application approval whereby users do not need API Administrator or Organization Administrator approval.
	AutoApproveApplications bool `json:"autoApproveApplications,omitempty"`
	// Enables/disables user administration to the Organization Administrators.
	DelegateUserAdministration bool `json:"delegateUserAdministration,omitempty"`
	// Enables/disables application administration to the Organization Administrators.
	DelegateApplicationAdministration bool `json:"delegateApplicationAdministration,omitempty"`
	// The network host and port that serves as the default virtual host from which API Manager registered API will be accessible through.
	ApiDefaultVirtualHost string `json:"apiDefaultVirtualHost,omitempty"`
	// Enable routing to APIs on the same base path.
	ApiRoutingKeyEnabled bool `json:"apiRoutingKeyEnabled,omitempty"`
	// An additional routing key is required to support multiple APIs registered on the same base path. This indicates where to look for the value.
	ApiRoutingKeyLocation string `json:"apiRoutingKeyLocation,omitempty"`
	// The 'from' address used in emails.
	EmailFrom string `json:"emailFrom,omitempty"`
	// An email address where undeliverable emails will be bounced to.
	EmailBounceAddress string `json:"emailBounceAddress,omitempty"`
	// Enables/disables API promotion via policy.
	PromoteApiViaPolicy bool `json:"promoteApiViaPolicy,omitempty"`
	// Enables/disables Global policies.
	GlobalPoliciesEnabled bool `json:"globalPoliciesEnabled,omitempty"`
	// The Global Request Policy to be executed for all Frontend API calls. Must be a valid policy ID. Can be null to indicate no policy
	GlobalRequestPolicy string `json:"globalRequestPolicy,omitempty"`
	// The Global Response Policy to be executed for all Frontend API calls. Must be a valid policy ID. Can be null to indicate no policy
	GlobalResponsePolicy string `json:"globalResponsePolicy,omitempty"`
	// Enables/disables API Manager fault handlers.
	FaultHandlersEnabled bool `json:"faultHandlersEnabled,omitempty"`
	// The Global Fault Handler Policy to be used by all Frontend APIs in the event of an error. Must be a valid policy ID. Can be null to indicate no policy
	GlobalFaultHandlerPolicy string `json:"globalFaultHandlerPolicy,omitempty"`
	BaseOAuth bool `json:"baseOAuth,omitempty"`
	// External user name
	ExternalUserName string `json:"externalUserName,omitempty"`
	// External user description
	ExternalUserDescription string `json:"externalUserDescription,omitempty"`
	// External user phone
	ExternalUserPhone string `json:"externalUserPhone,omitempty"`
	// External user email
	ExternalUserEmail string `json:"externalUserEmail,omitempty"`
	// External user organization name
	ExternalUserOrganization string `json:"externalUserOrganization,omitempty"`
	// External user role
	ExternalUserRole string `json:"externalUserRole,omitempty"`
	// External user enabled
	ExternalUserEnabled string `json:"externalUserEnabled,omitempty"`
	// Idle session timeout in milliseconds
	SessionIdleTimeout int64 `json:"sessionIdleTimeout"`
	// Is trial enabled
	IsTrial bool `json:"isTrial,omitempty"`
	// Default trial duration in days
	DefaultTrialDuration int32 `json:"defaultTrialDuration,omitempty"`
	// Login name validation regex
	LoginNameRegex string `json:"loginNameRegex,omitempty"`
	// The Version information of API Manager.
	ProductVersion string `json:"productVersion,omitempty"`
	// The operating system on which API Manager server is running.
	Os string `json:"os,omitempty"`
	// The architecture of the operating system on which the API Manager server is running. Supported values: [ win-x86-32, linux-x86-64 ]
	Architecture string `json:"architecture,omitempty"`
}
