/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// BackendBlob Backend blob export definition.
type BackendBlob struct {
	// Unique identifier
	Id string `json:"id,omitempty"`
	// Type of blob
	Type string `json:"type,omitempty"`
	// Base64 encoded API
	Blob string `json:"blob,omitempty"`
	// API name
	Name string `json:"name,omitempty"`
	// Original URL
	ImportURL string `json:"importURL,omitempty"`
}
