/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// SwaggerSecurityDevice Security Device details.
type SwaggerSecurityDevice struct {
	// Type identifier for the device. Possible Values: HTTPBasicSecurityDevice, OAuthSecurityDevice, AWSRESTRequestSecurityDevice, AWSQueryStringRequestSecurityDevice, APIKeyOnlySecurityDevice, APIKeyAndSecretSecurityDevice, TwoWaySSLSecurityDevice
	Type string `json:"type,omitempty"`
	// Textual display name for the device
	TypeDisplayName string `json:"typeDisplayName,omitempty"`
	// Name of the device
	Name string `json:"name,omitempty"`
	// Order of preference, zero being highest. Devices will attempt to authenticate the incoming request using this order of preference.
	Order int32 `json:"order,omitempty"`
	// The list of scopes defined for the security device.
	Scopes []string `json:"scopes,omitempty"`
	// Specifies how scopes will be matched. Possible values: [ Any, All ]
	ScopeMatching string `json:"scopeMatching,omitempty"`
}
