/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// SecurityProfile Inbound security profile.
type SecurityProfile struct {
	// Unique name of the Profile
	Name string `json:"name,omitempty"`
	// Indicates that this is the default profile.  There can be only one default.
	IsDefault bool `json:"isDefault,omitempty"`
	// List of SecurityDevice for this security profile
	Devices []SecurityDevice `json:"devices,omitempty"`
}
