/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// MetricTimeline The metrics timeline report is a report of a specific metric over a period of time.
type MetricTimeline struct {
	Id string `json:"id,omitempty"`
	// The metric name.
	Name string `json:"name,omitempty"`
	// The time series.
	Series []Series `json:"series,omitempty"`
}
