/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// ApiPromotion API promotion package.
type ApiPromotion struct {
	Frontend FrontendExport `json:"frontend,omitempty"`
	Backend BackendExport `json:"backend,omitempty"`
	// Export version
	ExportVersion int32 `json:"exportVersion,omitempty"`
}
