/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// Authorization struct for Authorization
type Authorization struct {
	// An identifier
	Id string `json:"id,omitempty"`
	// Schema title
	Title string `json:"title,omitempty"`
	// Description of the Schema
	Description string `json:"description,omitempty"`
	// The format ex: int32, int64, float, double, byte, binary, date, date-time or password
	Format string `json:"format,omitempty"`
	// Specifies if the parameter is required
	Required []string `json:"required,omitempty"`
	// Not used beacause our model does not support inline nested types
	Properties map[string]SchemaObject `json:"properties,omitempty"`
	Items SchemaObject `json:"items,omitempty"`
	// if the schema is an array specifies the items type
	Example map[string]interface{} `json:"example,omitempty"`
	Discriminator string `json:"discriminator,omitempty"`
	// Denotes how the API key must be passed. Valid values are 'header' or 'query'.
	PassAs string `json:"passAs,omitempty"`
	// The name of the header or query parameter to be used when passing the API key.
	Keyname string `json:"keyname,omitempty"`
	// The list of OAuth scopes.
	Scopes []Scope `json:"scopes,omitempty"`
	GrantTypes GrantTypes `json:"grantTypes,omitempty"`
	// A Reference to a definition on definitions object
	Ref string `json:"$ref,omitempty"`
	// Default value for this schema if it is applicable
	Default map[string]interface{} `json:"default,omitempty"`
	// The authorization type.  One of: basicAuth, apiKey, oauth2, none
	Type string `json:"type,omitempty"`
	Enum []string `json:"enum,omitempty"`
}
