/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// AlertConfig API alert system configuration
type AlertConfig struct {
	RunSysquotaExceeded bool `json:"runSysquotaExceeded,omitempty"`
	RunSysquotaWarning bool `json:"runSysquotaWarning,omitempty"`
	RunAppquotaExceeded bool `json:"runAppquotaExceeded,omitempty"`
	RunAppquotaWarning bool `json:"runAppquotaWarning,omitempty"`
	QuotaOverrideChanged bool `json:"quotaOverrideChanged,omitempty"`
	QuotaOverrideDeleted bool `json:"quotaOverrideDeleted,omitempty"`
	QuotaDefaultChanged bool `json:"quotaDefaultChanged,omitempty"`
	QuotaSystemChanged bool `json:"quotaSystemChanged,omitempty"`
	OrganizationCreate bool `json:"organizationCreate,omitempty"`
	OrganizationDelete bool `json:"organizationDelete,omitempty"`
	OrganizationEnable bool `json:"organizationEnable,omitempty"`
	OrganizationDisable bool `json:"organizationDisable,omitempty"`
	OrganizationAddapi bool `json:"organizationAddapi,omitempty"`
	OrganizationRemoveapi bool `json:"organizationRemoveapi,omitempty"`
	OrganizationEnableapi bool `json:"organizationEnableapi,omitempty"`
	OrganizationDisableapi bool `json:"organizationDisableapi,omitempty"`
	AppdevRegister bool `json:"appdevRegister,omitempty"`
	AppdevApprove bool `json:"appdevApprove,omitempty"`
	AppdevDelete bool `json:"appdevDelete,omitempty"`
	AppdevEnable bool `json:"appdevEnable,omitempty"`
	AppdevDisable bool `json:"appdevDisable,omitempty"`
	AppdevResetpwd bool `json:"appdevResetpwd,omitempty"`
	ApplicationRegister bool `json:"applicationRegister,omitempty"`
	ApplicationApprove bool `json:"applicationApprove,omitempty"`
	ApplicationDelete bool `json:"applicationDelete,omitempty"`
	ApplicationEnable bool `json:"applicationEnable,omitempty"`
	ApplicationDisable bool `json:"applicationDisable,omitempty"`
	ApplicationRequestapi bool `json:"applicationRequestapi,omitempty"`
	ApplicationApproveapi bool `json:"applicationApproveapi,omitempty"`
	ApplicationRemoveapi bool `json:"applicationRemoveapi,omitempty"`
	ApplicationEnableapi bool `json:"applicationEnableapi,omitempty"`
	ApplicationDisableapi bool `json:"applicationDisableapi,omitempty"`
	ApicatalogEnable bool `json:"apicatalogEnable,omitempty"`
	ApicatalogDisable bool `json:"apicatalogDisable,omitempty"`
	ApiproxyPublish bool `json:"apiproxyPublish,omitempty"`
	ApiproxyDeprecate bool `json:"apiproxyDeprecate,omitempty"`
	ApiproxyUndeprecate bool `json:"apiproxyUndeprecate,omitempty"`
	ApiproxyRetire bool `json:"apiproxyRetire,omitempty"`
	ApiproxyUnpublish bool `json:"apiproxyUnpublish,omitempty"`
	// Specifies whether or not an alert will be generated when an application credential is created
	ApplicationcredentialsCreate bool `json:"applicationcredentialsCreate,omitempty"`
	// Specifies whether or not an alert will be generated when an application credential is updated
	ApplicationcredentialsUpdate bool `json:"applicationcredentialsUpdate,omitempty"`
	// Specifies whether or not an alert will be generated when an application credential is deleted
	ApplicationcredentialsDelete bool `json:"applicationcredentialsDelete,omitempty"`
	// Specifies whether or not an alert will be generated when an application credential is enabled
	ApplicationcredentialsEnable bool `json:"applicationcredentialsEnable,omitempty"`
	// Specifies whether or not an alert will be generated when an application credential is disabled
	ApplicationcredentialsDisable bool `json:"applicationcredentialsDisable,omitempty"`
}
