/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// BackendMethodExport Backend API method export.
type BackendMethodExport struct {
	// Internal use only.
	ApiId string `json:"apiId,omitempty"`
	// Internal use only.
	ApiMethodId string `json:"apiMethodId,omitempty"`
	// Internal use only.
	Op string `json:"op,omitempty"`
}
