/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// Topology struct for Topology
type Topology struct {
	Id string `json:"id,omitempty"`
	Version int32 `json:"version,omitempty"`
	Timestamp int64 `json:"timestamp,omitempty"`
	ProductVersion string `json:"productVersion,omitempty"`
	Hosts []Host `json:"hosts,omitempty"`
	Groups []Group `json:"groups,omitempty"`
	UniqueIdCounters map[string]int32 `json:"uniqueIdCounters,omitempty"`
	EmtEnabled bool `json:"emtEnabled,omitempty"`
	Services []Service `json:"services,omitempty"`
}
