/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// MetricField Queryable metric type information
type MetricField struct {
	// The metric type name
	MetricType string `json:"metricType,omitempty"`
	// The metric aggregate name
	AggregateName string `json:"aggregateName,omitempty"`
}
