/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// RemoteHost An API Manager-registered remote host.
type RemoteHost struct {
	// The unique identifier for the remote host
	Id string `json:"id,omitempty"`
	// The host name of the remote host
	Name string `json:"name"`
	// The host port of the remote host
	Port int32 `json:"port"`
	// Epoch/Unix time stamp when the remote host was created
	CreatedOn int64 `json:"createdOn,omitempty"`
	// The unique identifier for user that created the remote host
	CreatedBy string `json:"createdBy,omitempty"`
	// The organization identifier to which the remote host belongs
	OrganizationId string `json:"organizationId,omitempty"`
	// The maximum number of connections to open to a Remote Host. If the maximum number of connections has already been established, the API Gateway instance waits for a connection to drop or become idle before making another request. The default value is -1, meaning there is no limit
	MaxConnections int32 `json:"maxConnections,omitempty"`
	// Enables the API Gateway to use HTTP 1.1 when connecting to the remote host. Default value is false, meaning HTTP 1.0 is used
	AllowHTTP11 bool `json:"allowHTTP11,omitempty"`
	// If this option is set, the API Gateway will include the Content-Length HTTP header in all requests to this Remote Host. Default value is false.
	IncludeContentLengthRequest bool `json:"includeContentLengthRequest,omitempty"`
	// If this option is set, if the API Gateway receives a response from this Remote Host that contains a Content-Length HTTP header, it returns this length to the client. Default value is false.
	IncludeContentLengthResponse bool `json:"includeContentLengthResponse,omitempty"`
	// Adds a field to outbound TLS/SSL calls that shows the name that the client used to connect. Default value is false.
	OfferTLSServerName bool `json:"offerTLSServerName,omitempty"`
	// Ensures that the certificate presented by the server matches the name of the remote host being connected to. This prevents host spoofing and man-in-the-middle attacks. Default value is false.
	VerifyServerHostname bool `json:"verifyServerHostname,omitempty"`
	// If a connection to this remote host is not established within the time set in this field, the connection times out and the connection fails. Default value is 30000 milliseconds (30 seconds).
	ConnectionTimeout int64 `json:"connectionTimeout,omitempty"`
	// The maximum amount of time permitted between reading successive blocks of data. If the Active Timeout is exceeded, the API Gateway closes the connection. This prevents a Remote Host from closing the connection while sending data. Default value is 30000 milliseconds (30 seconds).
	ActiveTimeout int64 `json:"activeTimeout,omitempty"`
	// The maximum amount of time permitted to complete the transaction. Default value is 240000 milliseconds (4 minutes).
	TransactionTimeout int64 `json:"transactionTimeout,omitempty"`
	// The maximum amount of time that API Gateway waits after sending a message over a persistent connection to the Remote Host before it closes the connection. Default value is 15000 milliseconds (15 seconds).
	IdleTimeout int64 `json:"idleTimeout,omitempty"`
	// The maximum amount of data the API Gateway can receive per transaction. Default value is 20971520 bytes (20MiB).
	MaxReceiveBytes int64 `json:"maxReceiveBytes,omitempty"`
	// The maximum amount of data the API Gateway can transmit per transaction. Default value is 20971520 bytes (20MiB).
	MaxSendBytes int64 `json:"maxSendBytes,omitempty"`
	// The maximum amount of memory allocated to each request. Default value is 8192 bytes.
	InputBufferSize int64 `json:"inputBufferSize,omitempty"`
	// The maximum amount of memory allocated to each response. Default value is 8192 bytes.
	OutputBufferSize int64 `json:"outputBufferSize,omitempty"`
	// The period of time to cache addressing information after it has been received from the naming service. Default value is 300000 milliseconds (5 minutes)
	AddressCacheTimeout int64 `json:"addressCacheTimeout,omitempty"`
	// Specifies the size of the SSL session cache for connections to the remote host, which controls the number of idle SSL sessions that can be kept in memory. Default value is 32.
	SslSessionCacheSize int32 `json:"sslSessionCacheSize,omitempty"`
	// Specifies the HTTP content encodings that the API Gateway can accept from peers. Supported encodings: *deflate*, *gzip*. If no encodings are specified the default encoding is applied.
	InputEncodings []string `json:"inputEncodings,omitempty"`
	// Specifies the HTTP content encodings that the API Gateway can apply to outgoing messages. Supported encodings: *deflate*, *gzip*. If no encodings are specified the default encoding is applied.
	OutputEncodings []string `json:"outputEncodings,omitempty"`
	// Specifies whether to add the X-CorrelationID header to outbound messages
	ExportCorrelationId bool `json:"exportCorrelationId,omitempty"`
}
