/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// OAuthClient API Manager OAuth Credentials.
type OAuthClient struct {
	// The client ID to be used in OAuth flows
	Id string `json:"id,omitempty"`
	// The PEM encodeded certificate used in JWT flow
	Cert string `json:"cert,omitempty"`
	// The client application secret to be used in OAuth flows
	Secret string `json:"secret,omitempty"`
	// OAuth defines two client types, based on their ability to authenticate securely with the authorization server. Possible values public or confidential
	Type string `json:"type,omitempty"`
	// Flag disables the OAuth credentials so they can't be used in authentication
	Enabled bool `json:"enabled,omitempty"`
	// The URL where the server will redirect the to present authorization codes or access tokens depending on the OAuth flow being executed
	RedirectUrls []string `json:"redirectUrls,omitempty"`
	// The domains to allow access for browser-based clients
	CorsOrigins []string `json:"corsOrigins,omitempty"`
	// The unique identifier for user that generated the OAuth credentials
	CreatedBy string `json:"createdBy,omitempty"`
	// Epoch/Unix time stamp when the OAuth credentials was created
	CreatedOn int64 `json:"createdOn,omitempty"`
	// The application identifier associated with the OAuth credential
	ApplicationId string `json:"applicationId,omitempty"`
}
