/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// OAuthAppScope OAuth Application Scope
type OAuthAppScope struct {
	// The unique identifier for the oauth protected resource
	Id string `json:"id"`
	// The unique identifier for the application that has this scope
	ApplicationId string `json:"applicationId"`
	// The scope string
	Scope string `json:"scope,omitempty"`
	// Flag to indicate if this scope is one of the applications default scopes
	IsDefault bool `json:"isDefault,omitempty"`
}
