/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// Series A metric time series.
type Series struct {
	// The metric type name
	Name string `json:"name,omitempty"`
	// The amount of time, in milliseconds, between data points
	PointInterval int64 `json:"pointInterval,omitempty"`
	// The time of the first data point in milliseconds
	PointStart int64 `json:"pointStart,omitempty"`
	// The a metric measurement at a specific time interval
	Data []float32 `json:"data,omitempty"`
}
