/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// Organization API Manager organization
type Organization struct {
	// The unique identifier for the organization
	Id string `json:"id,omitempty"`
	// The name of the organization
	Name string `json:"name"`
	// The description of the organization
	Description string `json:"description,omitempty"`
	// The contact email address associated with the organization
	Email string `json:"email,omitempty"`
	// URI of the image to be used for this organization. To update the image, please refer to the API.
	Image string `json:"image,omitempty"`
	// Indicates that the organization is restricted.  Users in a restricted organization cannot see other users, and users cannot register for the organization using tokens.  Default is 'false'.
	Restricted bool `json:"restricted,omitempty"`
	// The virtual host associated with the organization
	VirtualHost string `json:"virtualHost,omitempty"`
	// Contact phone number of the organization
	Phone string `json:"phone,omitempty"`
	// Flag to indicate if this organization is enabled or not
	Enabled bool `json:"enabled,omitempty"`
	// Flag to indicate if this organization is enabled or not for API development.
	Development bool `json:"development,omitempty"`
	Dn string `json:"dn,omitempty"`
	// Epoch/Unix time stamp when the organization was created
	CreatedOn int64 `json:"createdOn,omitempty"`
	// Epoch/Unix time stamp when the trial starts
	StartTrialDate int64 `json:"startTrialDate,omitempty"`
	// Epoch/Unix time stamp when the trial expires
	EndTrialDate int64 `json:"endTrialDate,omitempty"`
	// Length of the trial in days
	TrialDuration int32 `json:"trialDuration,omitempty"`
	// Indicates if this Org is a trial or not
	IsTrial bool `json:"isTrial,omitempty"`
}
