/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// OAuthProtectedResource Scope and prefix information for OAuth protected resource.
type OAuthProtectedResource struct {
	// Oauth protected path
	Uriprefix string `json:"uriprefix,omitempty"`
	// List of scopes associated with the OAuth protected path
	Scopes []string `json:"scopes,omitempty"`
	// Oauth Scope
	Scope string `json:"scope,omitempty"`
	// Scope Description
	Description string `json:"description,omitempty"`
}
