/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// Operation An operation available to an API path.
type Operation struct {
	// An identifier
	Id string `json:"id,omitempty"`
	// Schema title
	Title string `json:"title,omitempty"`
	// Description of the Schema
	Description string `json:"description,omitempty"`
	// The format ex: int32, int64, float, double, byte, binary, date, date-time or password
	Format string `json:"format,omitempty"`
	// Specifies if the parameter is required
	Required []string `json:"required,omitempty"`
	// Not used beacause our model does not support inline nested types
	Properties map[string]SchemaObject `json:"properties,omitempty"`
	Items SchemaObject `json:"items,omitempty"`
	// if the schema is an array specifies the items type
	Example map[string]interface{} `json:"example,omitempty"`
	Discriminator string `json:"discriminator,omitempty"`
	// The HTTP method
	HttpMethod string `json:"httpMethod,omitempty"`
	// The nickname of the operation
	Nickname string `json:"nickname,omitempty"`
	// A short summary description of the operation
	Summary string `json:"summary,omitempty"`
	// A detailed description of the operation
	Notes string `json:"notes,omitempty"`
	// The return type of the method, e.g. void, array, or a type found in models
	ResponseClass string `json:"responseClass,omitempty"`
	// A list of possible response messages and their meanings
	ErrorResponses []ErrorResponse `json:"errorResponses,omitempty"`
	// The content types that the operation consumes
	Consumes []string `json:"consumes,omitempty"`
	// The content types that the operation produces
	Produces []string `json:"produces,omitempty"`
	// Authorizations
	Authorizations map[string][]map[string]interface{} `json:"authorizations,omitempty"`
	// The list of tags associated with this API operation. Each tag can have multiple values
	Tags map[string][]string `json:"tags,omitempty"`
	SecurityProfile SwaggerSecurityProfile `json:"securityProfile,omitempty"`
	// The documentation URL for the operation
	DocumentationUrl string `json:"documentationUrl,omitempty"`
	// Indicates that the API is CORS enabled
	Cors bool `json:"cors,omitempty"`
	// A list of accepted parameters
	Parameters []Parameter `json:"parameters,omitempty"`
	// A Reference to a definition on definitions object
	Ref string `json:"$ref,omitempty"`
	// Default value for this schema if it is applicable
	Default map[string]interface{} `json:"default,omitempty"`
	// The return type of the method, e.g. void, array, or a type found in models
	Type string `json:"type,omitempty"`
	Enum []string `json:"enum,omitempty"`
}
