/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// Method A method available on an API resource.
type Method struct {
	// The method identifier
	Id string `json:"id,omitempty"`
	// The API identifier to which this method belongs
	ApiId string `json:"apiId,omitempty"`
	// The API path
	Path string `json:"path,omitempty"`
	// The HTTP verb
	Verb string `json:"verb,omitempty"`
	// The name of the operation
	Name string `json:"name,omitempty"`
	// A short summary description of the operation
	Summary string `json:"summary,omitempty"`
	// A detailed description of the operation
	Description string `json:"description,omitempty"`
	// The return type of the method, e.g. void, array, or a type found in models
	ReturnType string `json:"returnType,omitempty"`
	// A list of accepted parameters
	Parameters []Parameter `json:"parameters,omitempty"`
	// A list of possible response messages and their meanings
	ResponseCodes []ResponseCode `json:"responseCodes,omitempty"`
	// The content types that the operation consumes
	Consumes []string `json:"consumes,omitempty"`
	// The content types that the operation produces
	Produces []string `json:"produces,omitempty"`
	// A list of properties associated with this API Method. The list of properties may vary, depending on the type of the parent API.
	Properties map[string]string `json:"properties,omitempty"`
}
