/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// ExternalClient API Manager external client
type ExternalClient struct {
	// The ID of the external client
	Id string `json:"id,omitempty"`
	// The 3rd party client ID. This client ID is provided by a 3rd party OAuth service and is used to map an application to an external client. This value is unique, i.e. no other application can specify the same client ID.
	ClientId string `json:"clientId,omitempty"`
	// Flag disables the external client so it can't be used in authentication
	Enabled bool `json:"enabled,omitempty"`
	// The unique identifier of the user that created the mapping
	CreatedBy string `json:"createdBy,omitempty"`
	// Epoch/Unix time stamp when the mapping was created
	CreatedOn int64 `json:"createdOn,omitempty"`
	// The domains to allow access for browser-based clients
	CorsOrigins []string `json:"corsOrigins,omitempty"`
}
