/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// PermissionDto API Manager application permission.
type PermissionDto struct {
	// The permission identifier
	Id string `json:"id,omitempty"`
	// The user identifier
	UserId string `json:"userId,omitempty"`
	// The privilege
	Permission string `json:"permission,omitempty"`
	// The unique identifier for user that create the permission
	CreatedBy string `json:"createdBy,omitempty"`
	// Epoch/Unix time stamp when the permission was created
	CreatedOn int64 `json:"createdOn,omitempty"`
}
