/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// AuthenticatedUserAttributes struct for AuthenticatedUserAttributes
type AuthenticatedUserAttributes struct {
	FirstLogin bool `json:"firstLogin,omitempty"`
	IsSSOLogin bool `json:"isSSOLogin,omitempty"`
	UserDn string `json:"userDn,omitempty"`
}
