/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// ParamValue Outbound parameter value.
type ParamValue struct {
	// The parameter name.
	Name string `json:"name,omitempty"`
	// The type of parameter type.  Can be one of: *body*, *query*, *path*, *form*, or *header*.
	ParamType string `json:"paramType,omitempty"`
	// The parameter data type.  Can be one of: *string*, *integer*, etc.
	Type string `json:"type,omitempty"`
	// The parameter value.  Can be a regular value, or a selector, e.g.: ${params.path.id}.
	Value string `json:"value,omitempty"`
	// Indicates whether or not the parameter is required for the backend API.
	Required bool `json:"required,omitempty"`
	// Indicates whether or not the parameter is excluded for the backend API.
	Exclude bool `json:"exclude,omitempty"`
	// Indicates whether or not the parameter is an additional parameter (does not replace an existing parameter).
	Additional bool `json:"additional,omitempty"`
}
