/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// FrontendExport Frontend API export definition.
type FrontendExport struct {
	// List of frontend API
	Apis []VirtualizedApi `json:"apis,omitempty"`
	// List of frontend API methods
	Methods []VirtualizedMethodExport `json:"methods,omitempty"`
	// List of backend API methods
	BackendMethods []BackendMethodExport `json:"backendMethods,omitempty"`
	// Image Export
	Imagedata map[string]string `json:"imagedata,omitempty"`
}
