/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// ApiDefinition An API definition.
type ApiDefinition struct {
	// A unique identifier.
	Id string `json:"id,omitempty"`
	// The name of the API.
	Name string `json:"name,omitempty"`
	// A summary of the API.
	Summary string `json:"summary,omitempty"`
	// A detailed description of the API.
	Description string `json:"description,omitempty"`
	// The API version.
	Version string `json:"version,omitempty"`
	// The base path is where the API service is hosted.
	BasePath string `json:"basePath,omitempty"`
	// The resource path is applied to **basePath** to provide the prefix for all API methods.
	ResourcePath string `json:"resourcePath,omitempty"`
	// The models/schema the that the API
	Models map[string]map[string]interface{} `json:"models,omitempty"`
	// The content types that the API consumes
	Consumes []string `json:"consumes,omitempty"`
	// The content types that the API produces
	Produces []string `json:"produces,omitempty"`
	// Indicates that the API definition is integral to a frontend API; that the API was imported to define the frontend API.
	Integral bool `json:"integral,omitempty"`
	// Epoch/Unix time stamp when the organization was created.
	CreatedOn int64 `json:"createdOn,omitempty"`
	// The identifier of the user that created the API.
	CreatedBy string `json:"createdBy,omitempty"`
	// The [Organization](Organization.html) identifier.
	OrganizationId string `json:"organizationId,omitempty"`
	// Indicates the type of service being imported. Possible values: rest, wsdl.
	ServiceType string `json:"serviceType,omitempty"`
	// Indicates whether or not an original definition is available
	HasOriginalDefinition bool `json:"hasOriginalDefinition,omitempty"`
	// Specifies the URL used to import the backend API definition.
	ImportUrl string `json:"importUrl,omitempty"`
	// A list of properties associated with this API.
	Properties map[string]string `json:"properties,omitempty"`
}
