/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// PortalTrafficListener A HTTP service listener.
type PortalTrafficListener struct {
	// The service listener identifier
	Id string `json:"id"`
	// The name of the service listener
	Name string `json:"name"`
	// The listener protocol
	Protocol string `json:"protocol"`
	// The listener port
	Port int32 `json:"port"`
	// The listener prefix
	Prefix string `json:"prefix,omitempty"`
	// The listener address
	Address string `json:"address"`
	// The listener URL
	Url string `json:"url,omitempty"`
}
