/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// ApiAccess API Access indicates whether access to an API is available
type ApiAccess struct {
	// Unique identifier for approval decisions (includes pending approvals)
	Id string `json:"id,omitempty"`
	// Virtualised REST API unique id
	ApiId string `json:"apiId,omitempty"`
	// The unique identifier for user that requested access
	CreatedBy string `json:"createdBy,omitempty"`
	// Pending or approved state
	State string `json:"state,omitempty"`
	// Epoch/Unix time stamp when the approval decision was created 
	CreatedOn int64 `json:"createdOn,omitempty"`
	// Flag disables access to an API for organization or application
	Enabled bool `json:"enabled,omitempty"`
}
