/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// SecurityDevice Inbound security device.
type SecurityDevice struct {
	// Unique name of the Security Device.
	Name string `json:"name,omitempty"`
	// The Security device type.  Values are one of: *apiKey*, *awsHeader*, *awsQuery*, *basic*, *authPolicy*, *oauth*, *oauthExternal*, *passThrough*, or *twoWaySSL*.
	Type string `json:"type,omitempty"`
	// Specifies the order in which this device will be invoked.
	Order int32 `json:"order,omitempty"`
	// List of device-specific properties.
	Properties map[string]string `json:"properties,omitempty"`
}
