/*
 * API Manager API v1.3
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.3.0
 * Contact: support@axway.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package apimgr
// CorsProfile CORS configuration profile.
type CorsProfile struct {
	// Unique name of the Profile
	Name string `json:"name,omitempty"`
	// Indicates that this is the default profile.  There can be only one default.
	IsDefault bool `json:"isDefault,omitempty"`
	// List of origins for this CORS Profile
	Origins []string `json:"origins,omitempty"`
	// List of headers...
	AllowedHeaders []string `json:"allowedHeaders,omitempty"`
	// List of headers...
	ExposedHeaders []string `json:"exposedHeaders,omitempty"`
	// Specifies whether or credentials are supported for APIs/API Methods employing this CORS Profile.
	SupportCredentials bool `json:"supportCredentials,omitempty"`
	// Specifies the amount of time responses to OPTIONS requests are stored, in seconds, in the preflight result cache
	MaxAgeSeconds int64 `json:"maxAgeSeconds,omitempty"`
}
